TOOLKIT=C:\compile stuff\Microsoft Visual C++ Toolkit 2003
PSDK=C:\compile stuff\WindowsSDK
CIV4_PATH=D:\games\civ4bts\Beyond the Sword\CvGameCoreDLL
YOURMOD=
YOURLOGS=C:\Users\Administrator\Documents\My Games\Beyond the Sword\Logs
