SOURCE_DIR = ..
# Stricter warnings. The code editor (.vcxproj) uses /W3 though (by default).
PROJECT_CFLAGS = /WX /W4
# Allow inline expansion of functions with an inline keyword even for debug builds
PROJECT_Debug_CFLAGS = /Ob1
# DLL-internal profiler: /DUSE_INTERNAL_PROFILER
# Time Stamp Counter profiler: /DUSE_TSC_PROFILER
# External profiler, e.g. Very Sleepy: No profile flags needed; profile builds always use Z7.
# Standard Firaxis profiler (not sure if this can work w/o access to the EXE): /DFP_PROFILE_ENABLE
# The Auto Play flag disables graphics updates known to be rare and costly b/c they may
#   skew profiling of the DLL. So far only affects map trades involving the active player.
PROJECT_Profile_CFLAGS = /DPROFILE_AI_AUTO_PLAY
PROJECT_LDFLAGS = /DEF:CvGameCoreDLL.def
PRECOMPILE_DEPENDENCIES = 
# Should use these extra flags for debugging (i.e. when debugging errors that
# aren't reproducible with non-optimizing debug builds). Replacing /O2
# with just e.g. /Oi /Ot /Ob1 is also worth a try, or a debug build without /RTC1;
# that would have to be done through the actual Makefile.
#PROJECT_DebugOpt_CFLAGS = /DFASSERT_ENABLE /Oy-
# Can use whole-program optimization along with debug symbols; it's just slow to compile.
# (But not recommended for profiling with Very Sleepy; I've seen it e.g. claim
# that _alldiv calls all sorts of GameCoreDLL functions.)
#PROJECT_DebugOpt_CFLAGS = /GL
