SOURCE_DIR = ..
# Stricter warnings. The code editor (.vcxproj) uses /W3 though (by default).
PROJECT_CFLAGS = /WX /W4
# Allow inline expansion of functions with an inline keyword even for debug builds
PROJECT_Debug_CFLAGS = /Ob1
# Should _not_ be set when inspecting disassembly as it will disable __forceinline
#PROJECT_DebugOpt_CFLAGS = /DFASSERT_ENABLE /Oy-
# Can use global optimizations along with debug symbols; it's just slow to compile.
#PROJECT_DebugOpt_CFLAGS = /GL
# DLL-internal profiler: /DUSE_INTERNAL_PROFILER
# Time Stamp Counter profiler: /DUSE_TSC_PROFILER
# External profiler, e.g. Very Sleepy: No profile flags needed; profile builds always use Z7.
# Standard Firaxis profiler (not sure if this can work w/o access to the EXE): /DFP_PROFILE_ENABLE
PROJECT_Profile_CFLAGS = /DUSE_INTERNAL_PROFILER
PROJECT_LDFLAGS = /DEF:CvGameCoreDLL.def
PRECOMPILE_DEPENDENCIES = 
