TOOLKIT=D:\cuv4stuff\compile_prereq_advciv\Microsoft Visual C++ Toolkit 2003 SP1
PSDK=D:\cuv4stuff\compile_prereq_advciv\Microsoft SDKs\Windows\6.0
CIV4_PATH=D:\cuv4stuff\CvGameCoreDLL
YOURMOD=E:\steam\steamapps\common\Sid Meier's Civilization IV Beyond the Sword\Beyond the Sword\Mods\Doto112Dev\
