TOOLKIT=C:\compile stuff\Microsoft Visual C++ Toolkit 2003
PSDK=C:\compile stuff\WindowsSDK
CIV4_PATH=D:\steam games\steamapps\common\Sid Meier's Civilization IV Beyond the Sword\Beyond the Sword\CvGameCoreDLL
YOURMOD=
